import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Next Shop',
    description: 'Generated by Next13 and Dummy JSON',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
          <header>
            <nav>
              <Link href='/'>Home</Link>
            </nav>
                </header>
                <main>{children}</main>
                <footer></footer>
            </body>
        </html>
    );
}
